### ISSUE TITLE
[タスク] ビール情報をローカルDBに登録する機能を実装する

### ISSUE THREAD

**Issue by p238049y** [p238049y/beer-collection-app#14]
### 目的
* 画面(以下に添付)は実装しているが、DBへの記録ができていないため、ビール情報をローカルDBに登録する機能を実装する必要がる
![image](https://user-images.githubusercontent.com/82100625/205440849-2b98df8f-2fce-40c9-bb37-0138157ed03e.png)

### 方針
1.  画像、ビール名、スタイル、アルコール度数、カロリーを入力後、右下のアイコンをクリックすると、DBに登録できるようにする
2. 画像、ビール名、スタイル、カロリーは必須項目とする

### 期待結果
1.  画像、ビール名、スタイル、アルコール度数、カロリーの情報が入力できること
2. 画像は写真ををインポートできること
3. カメラを起動するようにすること
4. 登録後、ホーム画面の最新のビール記録に記録した内容が登録されていること

**Comment by p238049y** [comment]
### バグ発生

どこかがnullとなっている

```dart
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: Null check operator used on a null value
#0      DbProvider.insertData (package:beer_collection/repository/beer/beer.dart:30:19)
#1      _BeerRecordAddPageState.build.<anonymous closure> (package:beer_collection/view/HomePage/BeerRecordAddPage/beer_record_add_page.dart:210:44)
#2      _BeerRecordAddPageState.build.<anonymous closure> (package:beer_collection/view/HomePage/BeerRecordAddPage/beer_record_add_page.dart:203:36)
#3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:1005:21)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:613:11)
#6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:298:5)
#7      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:232:7)
#8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src<…>
```


### 調査

```dart
flutter: 東京
flutter: 0
flutter: 234
flutter: 3.0
flutter:
flutter: /Users/a21-0150/Library/Developer/CoreSimulator/Devices/272DA3C4-C993-4810-B926-B81144A4196E/data/Containers/Data/Application/691B7D85-1207-4365-81DD-55799D176711/tmp/image_picker_24500E88-4127-4AD9-8E6F-1999C3B6EB7E-52971-000140C989F6DDC3.jpg
```

→ どうやら日付がnullのためインサートできないようだ

**Comment by p238049y** [comment]
### 修正後の動作確認

```dart
flutter: beerName: 東京ホワイト
flutter: beerStyle: 1
flutter: alcoholDegree: 5.0
flutter: calorie: 234
flutter: registryDateTime: 2022/12/17 00:00
```

日付が入っていることを確認したが、エラーは消えない

**Comment by p238049y** [comment]
### SQL文の見直し

```dart
  static Future<void> _createTable(Database db, int version) async {
    await db.execute(
      'CREATE TABLE $tableName(id INTEGER PRIMARY KEY AUTOINCREMENT, beer_name TEXT, beer_style INTEGER, alcohol_degree REAL, calorie INTEGER, image TEXT, registry_date_time TEXT)'
    );
  }
```

` 'CREATE TABLE $tableName(id INTEGER PRIMARY KEY AUTOINCREMENT, beer_name TEXT, beer_style INTEGER, alcohol_degree REAL, calorie INTEGER, image TEXT, registry_date_time TEXT)'`の末尾に`;`がないことを確認した。
`;`をつけて再確認すると実行できた

**Comment by p238049y** [comment]
### 動作確認

登録後に表示されていることを確認した
https://user-images.githubusercontent.com/82100625/208234920-d24f7fbd-4175-4033-bd44-2410c63811cc.mov
