### ISSUE TITLE
[タスク] プロフィール画面の実装

### ISSUE THREAD

**Issue by p238049y** [p238049y/beer-collection-app#42]
### 目的
* ヘルスケアのプロフィール画面をイメージに合わせて実装する
![image](https://user-images.githubusercontent.com/82100625/210311190-93191bf1-e841-4c7d-8f3a-d5ed243372e7.png)

### 方針
1. イメージに合わせて実装する
2. 登録案内画面を作成したい

### 期待結果
1. プロフィール画面に遷移した際に自分の登録した内容が表示されること

**Comment by p238049y** [comment]
### 番外編

```dart
SystemChrome.setSystemUIOverlayStyle(
  const SystemUiOverlayStyle(
    statusBarBrightness: Brightness.light,     // for iOS
    statusBarIconBrightness: Brightness.dark,  // for Android
  ),
```

statusBarBrightnessで指定してあげればステータスバーの文字色をBrightnessに合った色に変更することができる。

**Comment by p238049y** [comment]
### エラー

```dart
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: DatabaseException(Error Domain=FMDatabase Code=1 "no such table: user" UserInfo={NSLocalizedDescription=no such table: user}) sql 'INSERT INTO user (user_name, height, weight) VALUES (?, ?, ?)' args [タロー, 171.3, 67.9]
#0      wrapDatabaseException (package:sqflite/src/exception_impl.dart:11:7)
<asynchronous suspension>
#1      SqfliteDatabaseMixin.txnRawInsert.<anonymous closure> (package:sqflite_common/src/database_mixin.dart:463:14)
<asynchronous suspension>
#2      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33:16)
<asynchronous suspension>
#3      SqfliteDatabaseMixin.txnSynchronized (package:sqflite_common/src/database_mixin.dart:392:14)
<asynchronous suspension>
#4      UserDbProvider.insertUserData (package:beer_collection/repository/user/user.dart:30:5)
<asynchronous suspension>
#5      _ProfileAddPageState.build.<anonymous closure> (package:beer_collection/view/ProfilePage/ProfileAddPage/profile_add_page.dart:1<…>
```

追加ができない
→ "no such table: user" userテーブルがきちんと作成できていなかった

lib/repository/user/user.dartのpathの'beer.db'を'user.db'に変更する

```dart
  static Future<Database> initDb() async {
    String path = join(await getDatabasesPath(), 'user.db');
    return await openDatabase(path, version: 1, onCreate: _createTable);
  }
```

**Comment by p238049y** [comment]
### 途中経過

![スクリーンショット 2023-01-03 17 01 09](https://user-images.githubusercontent.com/82100625/210319863-a3e93616-c576-4d26-9ce2-d21e87da639f.png)

**Comment by p238049y** [comment]
### エラー

```dart
RangeError (index): Invalid value: Valid value range is empty: 0
```

初回にページ遷移した時に取得するデータがなく` userDate = userList[0];`でuserListが空であることが問題だった

### 方針
* userListが空の場合は` userDate = userList[0];`を飛ばすように修正

**Comment by p238049y** [comment]
### エラー文

```dart
The overflowing RenderFlex has an orientation of Axis.vertical.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be
seen. If the content is legitimately bigger than the available space, consider clipping it with a
ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
like a ListView.
The specific RenderFlex in question is: RenderFlex#4b383 relayoutBoundary=up9 OVERFLOWING:
  needs compositing
  creator: Column ← Padding ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ←
    CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
    _InkFeatures-[GlobalKey#e6805 ink renderer] ← NotificationListener<LayoutChangedNotification> ←
    PhysicalModel ← ⋯
  parentData: offset=Offset(16.0, 0.0) (can use size)
  constraints: BoxConstraints(0.0<=w<=358.0, 0.0<=h<=375.0)
  size: Size(358.0, 375.0)
  direction: vertical
  mainAxisAlignment: start
  mainAxisSize: max
  crossAxisAlignment: center
  verticalDirection: down
◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
════════════════════════════════════════════════════════════════════════════════════════════════════
[AXRuntimeCommon] AX Lookup problem - errorCode:1100 error:Permission denied portName:'com.apple.iphone.axserver' PID:49222 (
        0   AXRuntime                           0x00000001cc19ba8c CDC17371-8478-3982-936D-2AA23E6C61DC + 326284
        1   AXRuntime                           0x00000001cc150d5c _AXGetPortFromCache + 704
        2   AXRuntime                           0x00000001cc152688 AXUIElementPerformFencedActionWithValue + 564
        3   UIKit                               0x00000002179d9240 1E08AD1F-8154-3B7B-98BE-C064E7670933 + 934464
        4   libdispatch.dylib                   0x00000001a59aae6c E3EA4F63-5D11-342A-AF19-9F58DBC8E259 + 7788
        5   libdispatch.dylib                   0x00000001a59aca30 E3EA4F63-5D11-342A-AF19-9F58DBC8E259 + 14896
        6   libdispatch.dylib                   0x00000001a59b4124 E3EA4F63-5D11-342A-AF19-9F58DBC8E259 + 45348
        7   libdispatch.dylib                   0x00000001a59b4c80 E3EA4F63-5D11-342A-AF19-9F58DBC8E259 + 48256
        8   libdispatch.dylib                   0x00000001a59bf500 E3EA4F63-5D11-342A-AF19-9F58DBC8E259 + 91392
        9   libsystem_pthread.dylib             0x00000002176a90bc _pthread_wqthread + 288
        10  libsystem_pthread.dylib             0x00000002176a8e5c start_wqthread + 8
)
```

描画する内容がオーバーフローしていることを怒っている
→ SingleChildScrollViewを使って、画面外までUIが広がってしまうことを防ぐ
今回は以下を使用する

```dart
// Column(縦にスクロールが必要な場合)
SingleChildScrollView(
  child: Column(),
),
```

参考：https://atsu-developer.net/389/
https://zenn.dev/engineerhikaru/books/ecf839ce7d0591bb203b/viewer/fa941f720f5358fa99b1

**Comment by p238049y** [comment]
https://user-images.githubusercontent.com/82100625/211150773-076a168f-6b8d-4ba6-8732-95fde66a0972.MOV
