### ISSUE TITLE
[タスク] アイコンを作成する

### ISSUE THREAD

**Issue by p238049y** [p238049y/beer-collection-app#49]
### 目的
* アプリのアイコンを作成する

### 方針
* アプリのアイコンを作成する
* https://cacoo.com/ja/blog/how-to-create-app-icons-easily-with-cacoo/　を使ってみるか
* https://naoya-ono.com/swift/create-appicon/　も参考になりそう

### 期待結果
* アプリのアイコンをデフォルトから差し替えること

**Comment by p238049y** [comment]
[flutterでアプリアイコンをデフォルトから変更する方法](https://zenn.dev/kyo9bo/articles/196e949cc9dd3a)を参考にアイコンを設定する

**Comment by p238049y** [comment]
<img width="208" alt="image" src="https://user-images.githubusercontent.com/82100625/212547600-7c2b4bf0-5d8a-4dc6-b80c-680d1d12a98c.png">

アイコンを作成
→ 1024 と 512を作成する

**Comment by p238049y** [comment]
### エラー

```dart

✓ Successfully generated launcher icons
Unhandled exception:

✗ ERROR: InvalidConfigException 
Cannot not find minSdk from android/app/build.gradle or android/local.propertiesSpecify minSdk in either android/app/build.gradle or android/local.properties
#0      createIconsFromConfig (package:flutter_launcher_icons/main.dart:96:7)
#1      createIconsFromArguments (package:flutter_launcher_icons/main.dart:60:7)
#2      main (file:///Users/a21-0150/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.9.3/bin/main.dart:7:26)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
pub finished with exit code 255
```

androidではエラーが出る

**Comment by p238049y** [comment]
![image](https://user-images.githubusercontent.com/82100625/212548890-675a13fa-a4ff-4225-9a1d-17c40c8dfbb6.jpeg)
