### ISSUE TITLE
[バグ] Androidの端末で登録したビール情報の画像がホーム画面に表示されない

### ISSUE THREAD

**Issue by p238049y** [p238049y/beer-collection-app#61]
### 目的
* Androidの端末で登録したビール情報の画像がホーム画面に表示されない。これを解消する
* ホーム画面ではない画面では表示される
* iosでは問題なく表示される

|Android|ios|
|--|--|
|<img width="250" alt="image" src="https://user-images.githubusercontent.com/82100625/212699932-c13445f7-4d4d-417a-b401-70f7769a20d0.jpeg">|<img width="250" alt="image" src="https://user-images.githubusercontent.com/82100625/212700003-c526e9be-54a0-42be-8c4c-273c8a173189.png">|

Androidでのビール詳細画面
<img width="250" alt="image" src="https://user-images.githubusercontent.com/82100625/212699812-5b2ffa83-9ac3-4a20-9797-5f95959b21a7.jpeg">

### 方針
1. コードの調査
2. 設定ファイルを確かめる

### 期待結果
1.  ホーム画面にビール情報の画像が表示されること

### 参考文献
* hoge

**Comment by p238049y** [comment]
![image](https://user-images.githubusercontent.com/82100625/212699812-5b2ffa83-9ac3-4a20-9797-5f95959b21a7.jpeg)

**Comment by p238049y** [comment]
### エラーメッセージ

```dart
Another exception was thrown: Unable to load asset: /data/user/0/com.example.beer_collection/cache/image_picker4944774861852335939.jpg
```

以下の記事をチェックする
https://kamotora.net/system/flutter/fluttererror-unable-to-load-asset/

**Comment by p238049y** [comment]
### エラー

```dart
======== Exception caught by image resource service ================================================
The following assertion was thrown resolving an image codec:
Unable to load asset: /data/user/0/com.example.beer_collection/cache/image_picker8491409629021241639.jpg

When the exception was thrown, this was the stack: 
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:237:7)
<asynchronous suspension>
#1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:658:14)
<asynchronous suspension>
Image provider: AssetImage(bundle: null, name: "/data/user/0/com.example.beer_collection/cache/image_picker8491409629021241639.jpg")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#c6742(), name: "/data/user/0/com.example.beer_collection/cache/image_picker8491409629021241639.jpg", scale: 1.0)
====================================================================================================
```

**Comment by p238049y** [comment]
[公式:image_picker](https://pub.dev/packages/image_picker)より、

```
Note: Images and videos picked using the camera are saved to your application's local cache, and should therefore be expected to only be around temporarily. If you require your picked image to be stored permanently, it is your responsibility to move it to a more permanent location.
```
→ カメラで撮影した画像や映像は端末内のキャッシュに保存されるようだ。`/data/user/0/com.example.beer_collection/cache/image_picker8491409629021241639.jpg`からわかるように/cache配下にファイルが存在することがわかる

**Comment by p238049y** [comment]
### コードに注目

ホーム画面の画像を表示するwidget`lib/view/HomePage/BeerScreen/beer_screen.dart`

```dart
    Container(
        height: 180,
        decoration: BoxDecoration(
          color: Styles.primaryColor,
          borderRadius: BorderRadius.circular(16),
          image: DecorationImage(
            fit: BoxFit.cover,
            image: AssetImage(beer.image),
          ),
        ),
      ),
```

ビール詳細画面(lib/view/HomePage/BeerListPage/BeerRecordDetailPage/beer_record_detail_page.dart)の画像表示部分

```dart
  SizedBox(
      width: 350,
      height: 250,
      child: Image.file(File(beerData.image))),
```

beer_screen.dartはAssetImageクラスを使って、asset配下の `beer.image`を探そうとしている
asset配下に登録した画像は存在しないため、Unable to load asset:というエラーが出る

beer_record_detail_page.dartはImage.fileを使ってbeerData.imageのファイルを探そうとしている
これはbeerData.imageのパスの画像ファイルを表示しようとしている
beer_screen.dartもこのように書き換えればいい！

### 修正案
`image: AssetImage(beer.image),`を`image: FileImage(File(beer.image)),`に書き換える

**Comment by p238049y** [comment]
![image](https://user-images.githubusercontent.com/82100625/212722113-5115183d-ad64-43d9-8947-0d04377cbe7f.jpeg)
