### ISSUE TITLE
[バグ] Android版のアプリをインストールするとクラッシュし、アプリが開けなくなる

### ISSUE THREAD

**Issue by p238049y** [p238049y/beer-collection-app#70]
### 事象
* Android版のアプリをインストールするとクラッシュし、アプリが開けなくなる

### ログ

```log
Launching lib/main.dart on Pixel 3 in debug mode...
Running Gradle task 'assembleDebug'...                              7.8s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                 4.4s
E/AndroidRuntime(24862): FATAL EXCEPTION: main
E/AndroidRuntime(24862): Process: io.github.p2388049y.beer_collection, PID: 24862
E/AndroidRuntime(24862): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{io.github.p2388049y.beer_collection/io.github.beer_collection.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "io.github.beer_collection.MainActivity" on path: DexPathList[[zip file "/data/app/~~MYvFqUZsHCT1CJazOfdjbA==/io.github.p2388049y.beer_collection-_woBnE7EGjoNSwCwo74bFA==/base.apk"],nativeLibraryDirectories=[/data/app/~~MYvFqUZsHCT1CJazOfdjbA==/io.github.p2388049y.beer_collection-_woBnE7EGjoNSwCwo74bFA==/lib/arm64, /data/app/~~MYvFqUZsHCT1CJazOfdjbA==/io.github.p2388049y.beer_collection-_woBnE7EGjoNSwCwo74bFA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /product/lib64]]
E/AndroidRuntime(24862):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3582)
E/AndroidRuntime(24862):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
E/AndroidRuntime(24862):        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
E/AndroidRuntime(24862):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(24862):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(24862):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
E/AndroidRuntime(24862):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(24862):        at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(24862):        at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(24862):        at android.app.ActivityThread.main(ActivityThread.java:7898)
E/AndroidRuntime(24862):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24862):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(24862):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime(24862): Caused by: java.lang.ClassNotFoundException: Didn't find class "io.github.beer_collection.MainActivity" on path: DexPathList[[zip file "/data/app/~~MYvFqUZsHCT1CJazOfdjbA==/io.github.p2388049y.beer_collection-_woBnE7EGjoNSwCwo74bFA==/base.apk"],nativeLibraryDirectories=[/data/app/~~MYvFqUZsHCT1CJazOfdjbA==/io.github.p2388049y.beer_collection-_woBnE7EGjoNSwCwo74bFA==/lib/arm64, /data/app/~~MYvFqUZsHCT1CJazOfdjbA==/io.github.p2388049y.beer_collection-_woBnE7EGjoNSwCwo74bFA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /product/lib64]]
E/AndroidRuntime(24862):        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
E/AndroidRuntime(24862):        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(24862):        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(24862):        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
E/AndroidRuntime(24862):        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
E/AndroidRuntime(24862):        at android.app.Instrumentation.newActivity(Instrumentation.java:1332)
E/AndroidRuntime(24862):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3569)
E/AndroidRuntime(24862):        ... 12 more

```

参考文献：https://teratail.com/questions/93886

**Comment by p238049y** [comment]
### 原因

```java
// android/app/src/main/AndroidManifest.xml
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{io.github.p238049y.beer_collection/io.github.beer_collection.MainActivity}:
```

android/app/src/main/AndroidManifest.xmlの`android:name`が`io.github.p238049y.beer_collection.MainActivity`とするところを`io.github.beer_collection.MainActivity`となっていたので、` Unable to instantiate activity`となり、クラッシュしていた。

### 方針
`io.github.p238049y.beer_collection.MainActivity`に変更する

**Comment by p238049y** [comment]
確認したのでマージします
